Docs update
Quahu/Qmmands pull request #14
Opened 2019-10-01 06:44 UTC by TheCasino

Don't merge yet

2019-10-01 09:00 UTC, Emzi0767 commented
You do realize you can mark a PR as draft

2019-10-01 09:01 UTC, TheCasino commented
@Emzi0767 I did not

2019-10-02 21:05 UTC, Quahu requested changes

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/Attributes/Checks/ParameterCheckAttribute.cs
> +        ///     Initialises a new <see cref="ParameterCheckAttribute"/> with the predicate of supported <see cref="Type"/>s.
We should word this differently. Something like "predicate which determines which types are supported"?

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/Attributes/Commands/CommandAttribute.cs
> +        /// <param name="aliases"> The aliases of the command. </param>
This would be inconsistent with the other attributes.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/Attributes/Commands/PriorityAttribute.cs
> +        ///    The <see cref="CommandService"/> will try to execute higher priority commands first.
`<see cref="Command">s`

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/Attributes/Modules/GroupAttribute.cs
> +        /// <param name="aliases"> The aliases of the module. </param>
This would be inconsistent with the other attributes.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/CommandService.cs
> +        /// </remarks>
I disagree with this being moved to remarks due to IntelliSense still not supporting them.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/CommandService.cs
> +        /// </remarks>
I disagree with this being moved to remarks due to IntelliSense still not supporting them.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
🤔

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/ICommandService.cs
> +        /// </remarks>
Same as in CommandService.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/ICommandService.cs
> +        /// </remarks>
Same as in CommandService.

2019-10-02 21:05 UTC, Quahu commented on src/Qmmands/Mapping/CommandMappingException.cs
> +        ///     Gets the segment of the map this exception occurred at.
The segment might not necessarily have been mapped before. Would "Gets the segment to map <ins>that</ins> this exception occurred for." make more sense?

2019-10-03 19:11 UTC, TheCasino commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
With how this is written `if it has not been added before` serves as extra non-key information

2019-10-03 19:12 UTC, Quahu commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
And the commas are incorrect?

2019-10-03 19:33 UTC, TheCasino commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
not exactly, just the use-case of brackets

2019-10-03 19:39 UTC, Quahu commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
Parentheses. 🙃

2019-10-03 19:40 UTC, Emzi0767 commented
@TheCasino you're wrong

2019-10-03 19:42 UTC, Quahu requested changes

2019-10-03 19:42 UTC, Quahu commented on src/Qmmands/Attributes/Commands/CommandAttribute.cs
> +        /// <param name="aliases"> The aliases to set1. </param>
1

2019-10-03 19:42 UTC, k-boyle commented
> @TheCasino you're wrong

![image](https://user-images.githubusercontent.com/17115277/66158715-59b5ba00-e61e-11e9-82ce-a8a09af48373.png)
uhuh

2019-10-03 19:44 UTC, Emzi0767 commented
![listen here you lil'](https://i.kym-cdn.com/entries/icons/original/000/017/372/ClmrSzk.jpg.png)

2019-10-03 19:55 UTC, merged

2019-10-03 20:51 UTC, Raunow commented on src/Qmmands/CommandService.cs
> +        ///     Sets and adds (if it has not been added before) an <see cref="IArgumentParser"/> as the default parser.
[Parenthetical Commas](http://drmarkwomack.com/a-writing-handbook/punctuation/commas/parenthetical-commas/)